services:
  mongodb:
    image: mongo:latest
    container_name: email-analyzer-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: email-analyzer
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: email-analyzer-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/email-analyzer?authSource=admin
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend/.env:/app/.env:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email-analyzer-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  mongodb_data:
